feature/products
andrey-korchevniy/ice-cream-passion pull request #49
Opened 2022-01-16 19:07 UTC by Liubov1102

mob version

2022-01-16 20:55 UTC, andrey-korchevniy requested changes

2022-01-16 20:55 UTC, andrey-korchevniy commented on src/sass/layout/_products.scss
> +.container {
этот класс - глобальный для всего макета, объявлен в боди, поэтому внесенные в него изменения потянут проблемы в других секциях. Если паддинги нужны только для этой секции, то лучше сделать специальный класс.

2022-01-16 20:55 UTC, andrey-korchevniy commented on src/sass/main.scss
> +@import './utils/mixin';
уже есть файл mixins. Зачем делать еще один? Можно добавить в него нужный код.

2022-01-17 07:20 UTC, Liubov1102 commented on src/sass/main.scss
> +@import './utils/mixin';
удалила

2022-01-17 07:20 UTC, Liubov1102 commented on src/sass/layout/_products.scss
> +.container {
исправила

2022-01-17 08:00 UTC, andrey-korchevniy approved these changes, later dismissed

2022-01-17 08:02 UTC, andrey-korchevniy approved these changes

2022-01-17 08:02 UTC, merged