Feature/products
andrey-korchevniy/ice-cream-passion pull request #6
Opened 2022-01-14 17:11 UTC by Liubov1102

add scss

2022-01-14 17:20 UTC, andrey-korchevniy requested changes

2022-01-14 17:20 UTC, andrey-korchevniy commented on src/partials/products.html
> +      <h2 class="products__title"></h2>
а почему нет текста в h2? Какой смысл тогда ставить этот тег?

2022-01-14 17:20 UTC, andrey-korchevniy commented on src/sass/layout/_products.scss
> +  padding: 121px 20px 98px 20px;
боковые падинги уже заданы container по 20px

2022-01-14 18:50 UTC, Liubov1102 commented on src/partials/products.html
> +      <h2 class="products__title"></h2>
исправлено

2022-01-14 18:50 UTC, Liubov1102 commented on src/sass/layout/_products.scss
> +  padding: 121px 20px 98px 20px;
исправлено

2022-01-15 06:51 UTC, andrey-korchevniy approved these changes

2022-01-15 06:52 UTC, merged